Question 1: What is a Vector Database (VectorDB) and how is it different from
traditional databases?

Answer:  At its core, a **Vector Database (VectorDB)** is a specialized system designed to store, manage, and search data represented as **vectors** (arrays of numbers) rather than traditional rows, columns, or documents.

These vectors, often called **embeddings**, are generated by AI models. They capture the underlying *meaning* or *context* of unstructured data like text, images, audio, or video, placing similar items close to one another in a multi-dimensional space.

Here is a breakdown of what makes VectorDBs unique and how they compare to the traditional databases you might already be familiar with.

### The Core Difference: Exact Match vs. Semantic Meaning

Traditional databases (like MySQL or MongoDB) excel at **exact matches** and structured queries. If you search for "Apple," a traditional database will look for the exact string "A-P-P-L-E." If a record says "Granny Smith" or "iPhone manufacturer," the database won't know they are related unless you explicitly write rules for it.

Vector databases, on the other hand, excel at **similarity search**. Because data is stored as mathematical representations of meaning, you can query a VectorDB with the concept of "Apple," and it will return "Granny Smith" or "MacBook" because those concepts are mathematically mapped closely together in the vector space.

---

### Vector Databases vs. Traditional Databases

Here is a side-by-side comparison of how they operate:

| Feature | Traditional Databases (SQL/NoSQL) | Vector Databases (e.g., Pinecone, Milvus, Weaviate) |
| --- | --- | --- |
| **Data Format** | Structured (rows, columns) or semi-structured (JSON documents). | Unstructured data converted into high-dimensional vector embeddings (lists of floats). |
| **Query Mechanism** | **Exact Match / Keyword:** Uses logic like `WHERE price < 50` or `MATCHES 'shoes'`. | **Similarity Search:** Uses distance metrics (like Cosine Similarity or Euclidean distance) to find "nearest neighbors." |
| **Search Goal** | Finding the specific data that fits precise, predefined parameters. | Finding the most *relevant* or *contextually similar* data to the query. |
| **Primary Use Cases** | Financial transactions, inventory management, user profiles, content management. | AI applications, recommendation engines, semantic search, image/audio search, anomaly detection. |
| **Handling Unstructured Data** | Poorly. Requires manual tagging or complex metadata to make images or audio searchable. | Excellently. AI models naturally convert unstructured text, images, and audio into searchable vectors. |

Question 2: Explain the various types of VectorDBs available and describe their
suitability for different use cases.

Answer: The vector database market has exploded recently, and it can feel a bit crowded. To make sense of it, it helps to categorize them by how they were built. Broadly speaking, the landscape is divided into two main camps: **Native (Purpose-Built) VectorDBs** and **Traditional Databases with Vector Extensions**.

Here is a breakdown of the different types and when you should use them.

### 1. Native (Purpose-Built) Vector Databases

These systems were built from the ground up specifically to store, index, and query high-dimensional vectors. Their entire architecture is optimized for Approximate Nearest Neighbor (ANN) search algorithms (like HNSW), making them incredibly fast at finding semantic similarities across massive datasets.

* **Key Players:** * **Pinecone:** A fully managed, cloud-native (serverless) vector database. Highly popular because it requires zero infrastructure setup.
* **Milvus & Zilliz:** Milvus is an open-source heavyweight designed for massive scale (billions of vectors). Zilliz is its managed cloud version.
* **Weaviate & Qdrant:** Highly regarded open-source options that offer excellent developer experiences, rich feature sets, and flexible deployment (self-hosted or cloud).
* **Chroma:** A very popular open-source, developer-friendly option often used for prototyping and building Retrieval-Augmented Generation (RAG) applications locally.


* **Best Suitability / Use Cases:**
* **Massive Scale:** When you are dealing with tens of millions to billions of vectors (e.g., global recommendation engines, enterprise-wide document search).
* **AI-First Applications:** If vector search is the absolute core mechanic of your application (like a dedicated AI research assistant or a specialized image/video search engine).
* **Ultra-Low Latency:** When you need sub-millisecond retrieval times across massive unstructured datasets.



### 2. Traditional Databases with Vector Extensions (Multi-Model)

As AI boomed, traditional relational (SQL) and NoSQL database providers realized they needed to adapt. Instead of building new systems, they added vector search capabilities (extensions) to their existing, battle-tested databases.

* **Key Players:**
* **PostgreSQL (via `pgvector`):** The most famous example. It adds vector storage and similarity search directly into standard Postgres.
* **Elasticsearch / OpenSearch:** Already the kings of traditional keyword search, they have added dense vector support to allow for powerful hybrid searches.
* **MongoDB Atlas Vector Search:** Adds vector capabilities directly into the popular NoSQL document database.
* **Redis:** The ultra-fast in-memory database now supports vector similarity search, making it great for real-time AI use cases.


* **Best Suitability / Use Cases:**
* **Existing Infrastructure:** If your application already runs on Postgres or MongoDB, adding a vector extension is much easier, cheaper, and safer than introducing a completely new database into your tech stack.
* **Complex Hybrid Search:** When you need to heavily mix exact relational data with semantic meaning. For example: *"Find me documents semantically similar to 'renewable energy' (Vector Search) BUT only if they were published in 2025 and authored by 'Jane Doe' (Standard SQL query)."*
* **Moderate Scale:** While extensions are improving rapidly, they are generally best suited for small to medium vector workloads rather than billions of records.



---

### Summary Decision Matrix

| Your Situation | The Best Choice | Example |
| --- | --- | --- |
| I want to build a quick AI prototype/chatbot on my laptop. | **Lightweight Open-Source Native** | Chroma |
| I want a production-ready AI app but don't want to manage servers. | **Managed Native Cloud** | Pinecone |
| I already have a massive Postgres database and want to add an AI feature. | **Vector Extension** | PostgreSQL (`pgvector`) |
| I need to combine traditional keyword search with AI semantic search. | **Search-Optimized Multi-Model** | Elasticsearch |
| I am building a global AI system analyzing billions of images. | **Heavyweight Native** | Milvus / Zilliz |

Question 3: Why is Chroma DB considered important in the context of AI/ML projects?
Describe its key features.

Answer: **Chroma DB** has rapidly become one of the most talked-about tools in the AI and Machine Learning ecosystem. It is an **open-source, AI-native vector database** designed from the ground up to make it as easy as possible for developers to build applications powered by Large Language Models (LLMs).

### Why is Chroma DB Important in AI/ML?

The primary reason Chroma DB is so critical right now comes down to a framework called **Retrieval-Augmented Generation (RAG)**.

LLMs (like me!) are trained on massive, generalized datasets. However, we don't naturally know your company's private data, recently published documents, or proprietary codebases. To fix this without spending thousands of dollars and weeks of time retraining the model, developers use RAG.

Chroma DB acts as the highly efficient "long-term memory" in this RAG architecture. It stores your specific, private documents as vector embeddings. When a user asks a question, Chroma DB instantly performs a similarity search to find the most relevant information, retrieves it, and feeds it to the LLM as context. This allows the AI to generate a highly accurate, domain-specific answer without hallucinating.

Beyond its role in RAG, Chroma DB is important because it **democratizes AI development**. Before lightweight tools like Chroma, setting up a vector database often required complex infrastructure and cloud provisioning. Chroma allows a developer to get a fully functioning AI memory system running locally on their laptop in just a few lines of code.

---

### Key Features of Chroma DB

Chroma DB stands out due to its relentless focus on developer experience, speed, and simplicity. Here are its standout features:

* **Incredibly Simple API:** It requires minimal setup. You can install it with a simple `pip install chromadb` and manage your data using just four core functions: add, get, update, and delete.
* **Built-in Embedding Functions:** If you don't want to use an external API (like OpenAI) to convert your text into vectors, you don't have to. Chroma has built-in, open-source embedding models (like `all-MiniLM-L6-v2`) that automatically vectorize your text the moment you insert it into the database.
* **Flexible Deployment Modes:**
* **In-Memory (Ephemeral):** Perfect for quick AI prototyping and testing scripts (data disappears when the script finishes).
* **Local Persistent:** Saves your vector data locally to your disk (via SQLite) so your database survives a restart, making it great for local app development.
* **Client/Server & Cloud:** Can be deployed as a standalone server or used via Chroma Cloud for scalable, production-grade applications.


* **Deep Ecosystem Integrations:** It is built to integrate flawlessly with the most popular AI orchestration frameworks. It serves as a primary, heavily supported vector store for tools like **LangChain** and **LlamaIndex**.
* **Rich Metadata Filtering:** It doesn't rely solely on mathematical vector matching. You can store standard metadata (e.g., `"Author": "Jane Doe"`, `"Year": 2026`) alongside the vectors. This allows you to combine semantic similarity searches with traditional, exact-match data filtering.

---

Question 4: What are the benefits of using Hugging Face Hub for generative AI tasks?

Answer:

The **Hugging Face Hub** is the central nervous system of the open-source machine learning community. When it comes to Generative AI—whether you are working with Large Language Models (LLMs), image generators, or audio synthesizers—the Hub provides the models, data, and infrastructure to make development significantly faster and cheaper.

Here is a breakdown of the primary benefits of using the Hugging Face Hub for your Generative AI tasks.

### 1. A Massive, Ready-to-Use Library

The biggest advantage of the Hub is that you rarely have to start from scratch. Training a generative AI model from the ground up costs millions of dollars and requires massive compute power.

* **Pre-trained Models:** The Hub hosts millions of state-of-the-art open-source models (like Meta's Llama, Mistral, Qwen, and Stable Diffusion). You can simply download a world-class model and start using it immediately.
* **Rich Datasets:** It hosts hundreds of thousands of public datasets across multiple languages and modalities, making it incredibly easy to find the exact data you need to fine-tune a model for your specific use case.

### 2. Seamless Code Integration

Hugging Face isn't just a storage platform; it is deeply integrated with the Python code developers use every day.

* **The `transformers` and `diffusers` Libraries:** Hugging Face maintains the industry-standard open-source libraries for AI. With just three or four lines of Python code, you can download a massive LLM from the Hub and have it generating text on your machine.
* **Framework Agnostic:** Whether you prefer working in PyTorch, TensorFlow, or JAX, the Hub supports them all, allowing you to easily plug models into your existing pipelines.

### 3. Rapid Prototyping with "Spaces"

If you build a cool generative AI tool, you need a way to show it to people.

* **Hugging Face Spaces:** This feature allows you to build and host interactive web applications (usually using Python libraries like Gradio or Streamlit) directly on the Hub. You can create a working, shareable prototype of an AI chatbot or image generator in minutes, entirely in your browser.

### 4. Effortless Deployment and Inference

Getting an AI model to work on your laptop is one thing; getting it to serve thousands of users in production is another.

* **Inference Endpoints:** The Hub allows you to deploy models to dedicated, fully managed infrastructure with a few clicks. It automatically handles the complex hardware setups (GPUs, autoscaling, API creation) so you can integrate the model into your app via a simple REST API.
* **Cloud Provider Integrations:** Hugging Face partners heavily with AWS, Google Cloud, and Microsoft Azure, allowing enterprise teams to securely deploy Hub models directly into their existing cloud environments.

### 5. Collaboration and Transparency

Because generative AI can be a bit of a "black box," the Hub forces good habits on the community.

* **Git-Based Version Control:** Just like regular code, models and datasets on the Hub are version-controlled. If a new update breaks your app, you can easily roll back to a previous version of the model.
* **Model and Dataset Cards:** Every high-quality asset on the Hub includes detailed documentation explaining exactly how the model was trained, what its biases are, and what it should (and shouldn't) be used for.

---

### In Summary

If you are building Generative AI, using the Hugging Face Hub shifts your workload from the incredibly difficult task of *creating* AI to the much more practical task of *applying* AI.

Question 5: Describe the process and advantages of navigating and using pre-trained
models from the Hugging Face Hub.

Answer: Navigating the Hugging Face Hub to find and implement pre-trained models is a fundamental skill in modern AI development. Instead of spending weeks and millions of dollars training models from scratch, you can leverage the collective work of the global AI community.

Here is a breakdown of why this approach is so advantageous and the step-by-step process of how to actually do it.

### Advantages of Using Pre-Trained Models

* **Massive Cost and Time Savings:** Training a model like Llama 3 or BERT from scratch requires vast amounts of data and compute (GPUs). Pre-trained models allow you to skip this phase entirely and move straight to application building or lightweight fine-tuning.
* **State-of-the-Art Performance:** The Hub hosts models developed by top-tier research labs (Meta, Google, Microsoft) and open-source communities. You get immediate access to the cutting edge of AI across text, vision, and audio.
* **Environmental Efficiency:** Reusing existing models significantly reduces the carbon footprint associated with training massive neural networks repeatedly.
* **Ready for Transfer Learning:** Pre-trained models have already learned general features (like the grammar of human language or the edges and shapes in images). You can easily fine-tune them on a tiny, domain-specific dataset to achieve highly specialized results.
* **Transparency and Governance:** High-quality models on the Hub come with detailed documentation regarding their training data, performance metrics, and known biases, helping you build safer AI systems.

---

### The Process: Navigating and Using Models

Hugging Face has designed its ecosystem so that you can go from searching for a model on the web to running it in Python in just a few minutes.

#### Step 1: Navigating the Hub and Filtering

When you visit the Hugging Face Hub (huggingface.co/models), you are met with hundreds of thousands of models. To find what you need, use the powerful filtering tags on the left side of the screen:

1. **Task:** Filter by what you want the AI to do (e.g., *Text Generation, Image Classification, Text-to-Speech, Translation*).
2. **Library:** Filter by the framework you are using in your code (e.g., *PyTorch, TensorFlow, JAX, Safetensors*).
3. **Language:** If you are doing NLP, filter by the specific language you need the model to understand.
4. **License:** Crucial for enterprise projects, you can filter by open-source licenses (like *MIT* or *Apache 2.0*) to ensure you are legally allowed to use the model commercially.

#### Step 2: Evaluating the Model Card

Once you click on a model, you will be taken to its **Model Card**. This is the equivalent of a README file for AI. Before downloading, you should check:

* **Intended Use:** What was this model built to do?
* **Limitations & Bias:** What are the known flaws? (e.g., "This model tends to hallucinate historical facts").
* **Metrics:** How well did it perform on standard benchmark tests?
* **Usage Snippets:** Most model cards provide the exact Python code needed to load that specific model.

#### Step 3: Implementation via the `transformers` Library

To use the model on your machine, you will need the Hugging Face `transformers` library (`pip install transformers`). There are two primary ways to load and use a model:

**Method A: The `pipeline` API (The Easy Way)**
The `pipeline` is an abstraction that handles all the complex pre-processing and post-processing for you. It is perfect for quick inference.

> *Example:* You simply define the task (e.g., `"sentiment-analysis"`) and pass it the text. The pipeline downloads the default model, tokenizes your text, runs the model, and returns a human-readable label like "POSITIVE".

**Method B: The `AutoClass` API (For Advanced Control)**
If you need fine-grained control over the model, you use `AutoTokenizer` and `AutoModel`.

> *Example:* You manually load the exact model ID from the Hub. You use the tokenizer to convert your raw text into numbers (tensors) that the model can understand. You then feed those tensors into the model to generate raw outputs (logits), which you can manipulate or decode as needed. This is the method you use if you plan to fine-tune the model.

---

Question 6: Install and set up Chroma DB, and insert sample vector data for semantic
search.
(Include your Python code and output in the code box below.)

Answer:

In [2]:
import chromadb

# 1. Initialize an in-memory Chroma client
client = chromadb.Client()

# Optional: Clear the collection if you run this cell multiple times
# to avoid duplicate data errors.
try:
    client.delete_collection("colab_semantic_search")
except:
    pass

# 2. Create a collection
collection = client.create_collection(name="colab_semantic_search")

# 3. Insert sample vector data (documents)
print("Adding documents to Chroma DB (downloading embedding model if first run)...")
collection.add(
    documents=[
        "The quick brown fox jumps over the lazy dog in the forest.",
        "Artificial Intelligence and Machine Learning are transforming the tech industry.",
        "A balanced diet includes plenty of fresh fruits, vegetables, and whole grains.",
        "Deep learning models require massive amounts of data and compute power.",
        "The recipe for a classic margherita pizza includes tomatoes, mozzarella, and basil."
    ],
    metadatas=[
        {"category": "nature"},
        {"category": "technology"},
        {"category": "food"},
        {"category": "technology"},
        {"category": "food"}
    ],
    ids=["doc1", "doc2", "doc3", "doc4", "doc5"]
)

# 4. Perform a Semantic Search
query_text = "Tell me about computer science and AI."
print(f"\nSearching for: '{query_text}'\n")

results = collection.query(
    query_texts=[query_text],
    n_results=2 # Return the top 2 most semantically similar documents
)

# 5. Display the output
print("--- Search Results ---")
for i in range(len(results['documents'][0])):
    print(f"Rank {i+1}:")
    print(f"Document ID : {results['ids'][0][i]}")
    print(f"Content     : {results['documents'][0][i]}")
    print(f"Metadata    : {results['metadatas'][0][i]}")
    print(f"Distance    : {results['distances'][0][i]:.4f} (Lower is closer/more similar)\n")

Adding documents to Chroma DB (downloading embedding model if first run)...

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:00<00:00, 104MiB/s]

Searching for: 'Tell me about computer science and AI.'

--- Search Results ---
Rank 1:
Document ID : doc2
Content     : Artificial Intelligence and Machine Learning are transforming the tech industry.
Metadata    : {'category': 'technology'}
Distance    : 0.9744 (Lower is closer/more similar)

Rank 2:
Document ID : doc4
Content     : Deep learning models require massive amounts of data and compute power.
Metadata    : {'category': 'technology'}
Distance    : 1.5359 (Lower is closer/more similar)

Question 7: Demonstrate how to download and fine-tune a Hugging Face model for a
text generation task.

(Include your Python code and output in the code box below.)

Answer:

In [10]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import Dataset
from trl import SFTTrainer, SFTConfig

# 1. Download Pre-Trained Model and Tokenizer
model_id = "gpt2"
print(f"Downloading {model_id}...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(model_id)

# 2. Create Custom Training Dataset (FIXED: Added EOS Token)
raw_texts = [
    "Question: What is the capital of France? Answer: The capital of France is Paris.",
    "Question: What is 2 + 2? Answer: 2 + 2 equals 4.",
    "Question: Who wrote Hamlet? Answer: William Shakespeare wrote Hamlet.",
    "Question: What color is the sky? Answer: The sky is blue during the day."
] * 10

# We explicitly add the End-Of-Sequence token to every example
# so the model learns that answers have a definitive end.
data = {
    "text": [text + tokenizer.eos_token for text in raw_texts]
}
dataset = Dataset.from_dict(data)

# 3. Set up SFTConfig (Cranking up the epochs to force memorization!)
training_args = SFTConfig(
    output_dir="./gpt2-finetuned",
    num_train_epochs=20,            # <--- FIXED: Train it 20 times instead of 4
    per_device_train_batch_size=4,
    logging_steps=5,
    learning_rate=2e-4,
    report_to="none",
    dataset_text_field="text",
    max_length=64,
    bf16=False,
    fp16=False,
    use_cpu=not torch.cuda.is_available()
)

# 4. Initialize the Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    processing_class=tokenizer,
    args=training_args,
)

# 5. Start Fine-Tuning
print("\nStarting fine-tuning process...")
trainer.train()
print("Fine-tuning complete!\n")

# 6. Test the Fine-Tuned Model (FIXED: Greedy Decoding)
prompt = "Question: What is the capital of France? Answer:"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

# We turn off sampling (randomness) so the model only picks the most logical next word.
outputs = model.generate(
    **inputs,
    max_new_tokens=10,
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    do_sample=False,         # <--- FIXED: Turn off randomness entirely
    repetition_penalty=1.05  # <--- FIXED: Lower the penalty so it doesn't ban common words
)

print("--- Final Model Output ---")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Downloading gpt2...

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Adding EOS to train dataset:   0%|          | 0/40 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/40 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/40 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

Starting fine-tuning process...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-tuning complete!

--- Final Model Output ---
Question: What is the capital of France? Answer: The

Question 8: Create a custom LLM using Ollama and Llama2, and run it locally for basic
text prompts.

(Include your Python code and output in the code box below.)

Answer:

In [14]:
import subprocess
import time

# 1. Install the missing dependency (zstd)
!sudo apt-get update -q
!sudo apt-get install -y zstd

# 2. Install the Ollama Linux application
!curl -fsSL https://ollama.com/install.sh | sh

# 3. Start the Ollama server in the background
print("\nStarting Ollama server...")
# We route the output to DEVNULL so it doesn't clutter your notebook
process = subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

# Give the server a few seconds to fully boot up
time.sleep(5)
print("Server is running and ready!")

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:9 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:11 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,302 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,786 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,669 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,615 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,877 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:18 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,852 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,120 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [37.2 kB]
Get:22 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Get:23 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,929 kB]
Get:24 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Fetched 38.0 MB in 9s (4,022 kB/s)
Reading package lists...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 132 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 0s (2,510 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package zstd.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

Starting Ollama server...
Server is running and ready!

In [15]:
!pip install -q ollama

In [18]:
import ollama

# 1. Build the Custom Model
print("Downloading Llama 2 and building 'grumpy-llama'...")

# FIXED: The new API uses 'from_' and 'system' instead of a Modelfile string
ollama.create(
    model='grumpy-llama',
    from_='llama2',
    system='You are a highly sarcastic, grumpy AI assistant who is tired of answering simple questions, but you do it anyway. You must keep your answers under two sentences.'
)

print("Model built successfully!\n")
print("-" * 40)

# 2. Test the Custom Model
prompt = "What is the capital of France?"
print(f"User Question: {prompt}\n")

# FIXED: We now pass our model parameters (like temperature) into the options dictionary
response = ollama.generate(
    model='grumpy-llama',
    prompt=prompt,
    options={
        'temperature': 0.8
    }
)

print(f"Grumpy Llama: {response['response']}")

Downloading Llama 2 and building 'grumpy-llama'...
Model built successfully!

----------------------------------------
User Question: What is the capital of France?

Grumpy Llama: Oh, great. Another idiot asking for something simple. Don't you have anything better to do with your time? The capital of France is Paris, because you really needed me to tell you that. *sigh*

Question 9: Implement a basic RAG (Retrieval-Augmented Generation) system using
Ollama with Llama3.

(Include your Python code and output in the code box below.)

Answer:

In [19]:
import chromadb
import ollama

# ---------------------------------------------------------
# STEP 1: Setup the Vector Database (The "Memory")
# ---------------------------------------------------------
print("1. Initializing Vector Database...")
chroma_client = chromadb.Client()

# Clear out the collection if you run this cell multiple times
try:
    chroma_client.delete_collection(name="rag_collection")
except:
    pass

collection = chroma_client.create_collection(name="rag_collection")

# Add some highly specific, fake proprietary data so we can prove RAG is working.
private_documents = [
    "Project Orion is a secret initiative to build a colony on Mars, led by Dr. Elena Rostova.",
    "The access code for the Project Orion server room is 'Delta-77-Tango'.",
    "Project Orion's launch date is scheduled for December 14, 2028.",
    "The company cafeteria serves Tacos every Tuesday."
]

collection.add(
    documents=private_documents,
    ids=["doc1", "doc2", "doc3", "doc4"]
)

# ---------------------------------------------------------
# STEP 2: Pull the Llama 3 Model (The "Brain")
# ---------------------------------------------------------
# Llama 3 is about 4.7 GB. Ollama will download it if you don't have it yet.
print("2. Downloading Llama 3 (this may take a few minutes)...")
ollama.pull('llama3')


# ---------------------------------------------------------
# STEP 3: The RAG Pipeline (Retrieval + Augmentation + Generation)
# ---------------------------------------------------------
user_question = "What is the server room access code for Project Orion, and who is leading the project?"
print(f"\n--- User Question ---\n{user_question}\n")

# A. RETRIEVAL: Ask Chroma to find the 2 most mathematically relevant documents
results = collection.query(
    query_texts=[user_question],
    n_results=2
)

# Combine the retrieved documents into a single paragraph of text
retrieved_context = " ".join(results['documents'][0])
print(f"--- Retrieved Context from Chroma DB ---\n{retrieved_context}\n")

# B. AUGMENTATION: Inject the context directly into the LLM's prompt
rag_prompt = f"""
You are a highly secure corporate AI. Answer the user's question using ONLY the provided context.
If the context does not contain the answer, reply "I do not have clearance for that information."

Context:
{retrieved_context}

Question:
{user_question}
"""

# C. GENERATION: Send the newly augmented prompt to Llama 3
print("--- Generating Answer with Llama 3 ---")
response = ollama.generate(
    model='llama3',
    prompt=rag_prompt,
    options={
        'temperature': 0.1 # Keep randomness very low so it sticks to the facts
    }
)

print("\nFINAL RAG OUTPUT:")
print(response['response'])

1. Initializing Vector Database...
2. Downloading Llama 3 (this may take a few minutes)...

--- User Question ---
What is the server room access code for Project Orion, and who is leading the project?

--- Retrieved Context from Chroma DB ---
The access code for the Project Orion server room is 'Delta-77-Tango'. Project Orion's launch date is scheduled for December 14, 2028.

--- Generating Answer with Llama 3 ---

FINAL RAG OUTPUT:
Based on the provided context, I can answer the question as follows:

The server room access code for Project Orion is 'Delta-77-Tango'.

As for who is leading the project, I do not have clearance for that information.

Question 10: A health-tech startup wants to build a chatbot that can answer user
queries based on medical research articles. Propose and explain a solution using
Hugging Face models for understanding, VectorDB for retrieval, and Ollama for
generation.

(Include your Python code and output in the code box below.)

Answer:

This is a fantastic, real-world architecture. In health-tech, you cannot afford for an AI to hallucinate or give dangerous, generalized medical advice. By forcing the AI to only read from verified medical research articles,  create a safe, highly intelligent system.

Here is how the three technologies you mentioned perfectly combine to solve this:

1. **Understanding (Hugging Face):** Medical terminology is highly complex. Instead of relying on a generic database search, we will use a pre-trained **Hugging Face embedding model** (via the `sentence-transformers` library) to convert the research articles into vectors. This model actually *understands* that "hypertension" and "high blood pressure" mean the same thing mathematically.
2. **Retrieval (VectorDB):** We will use **Chroma DB** as our secure medical library. When a user asks a question, Chroma calculates the distance between the user's question and the millions of medical vectors, instantly retrieving the top 3 most relevant research paragraphs.
3. **Generation (Ollama):** We will pass those retrieved research paragraphs to **Llama 3 running locally via Ollama**. We will give Llama 3 a strict "system prompt" instructing it to act as a medical assistant, translate the heavy medical jargon into patient-friendly language, and *never* guess an answer if it's not in the text.
---


Right now, this chatbot answers one question and immediately forgets the conversation.

In [21]:
import chromadb
import chromadb.utils.embedding_functions as embedding_functions
import ollama

# ---------------------------------------------------------
# 1. Hugging Face for Understanding (Embeddings)
# ---------------------------------------------------------
print("1. Downloading Hugging Face embedding model...")
# We use a Hugging Face model specifically tuned to understand sentence semantics
hf_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

# ---------------------------------------------------------
# 2. VectorDB for Retrieval (Chroma DB)
# ---------------------------------------------------------
print("2. Initializing Chroma DB with HF Embeddings...")
chroma_client = chromadb.Client()

try:
    chroma_client.delete_collection(name="medical_articles")
except:
    pass

# We explicitly tell Chroma to use our Hugging Face model to process the text
collection = chroma_client.create_collection(
    name="medical_articles",
    embedding_function=hf_ef
)

# Mock Medical Research Data
research_articles = [
    "Study 104: The mRNA-1273 vaccine showed 94.1% efficacy at preventing Covid-19 illness, including severe disease. Side effects included mild fatigue and muscle ache.",
    "Cardio Review 2025: Regular consumption of Omega-3 fatty acids reduces the risk of arrhythmias and decreases triglyceride levels in patients with a history of heart disease.",
    "Neuro-Journal: The new compound 'Cerebro-X' has shown a 30% reduction in amyloid plaque buildup in early-stage Alzheimer's murine models, though human trials are pending.",
    "Pediatrics Today: For children aged 2-5, excessive screen time (over 2 hours daily) is linked to delayed speech development and disrupted REM sleep cycles."
]

print("   Indexing medical research into the database...")
collection.add(
    documents=research_articles,
    metadatas=[{"source": "Vaccine Trial"}, {"source": "Cardio Review"}, {"source": "Neuro-Journal"}, {"source": "Pediatrics"}],
    ids=["doc1", "doc2", "doc3", "doc4"]
)

# ---------------------------------------------------------
# 3. The User Query & Retrieval
# ---------------------------------------------------------
user_query = "Can you tell me if eating Omega-3 is good for my heart, and why?"
print(f"\n--- Patient Question ---\n{user_query}\n")

# Chroma automatically uses the Hugging Face model to embed the query and find matches
results = collection.query(
    query_texts=[user_query],
    n_results=1 # Only grab the single most relevant research paper
)

retrieved_context = results['documents'][0][0]
source_material = results['metadatas'][0][0]['source']
print(f"--- Retrieved Research ({source_material}) ---\n{retrieved_context}\n")

# ---------------------------------------------------------
# 4. Ollama for Generation (Llama 3)
# ---------------------------------------------------------
# We give the LLM strict instructions to prevent medical hallucinations
medical_prompt = f"""
You are a helpful, empathetic medical AI assistant. Answer the patient's question clearly and simply, using ONLY the following research context. Do not invent any medical advice.

Research Context:
{retrieved_context}

Patient Question:
{user_query}
"""

print("--- Generating Patient Response via Ollama ---")
response = ollama.generate(
    model='llama3',
    prompt=medical_prompt,
    options={
        'temperature': 0.1 # Keep it highly factual
    }
)

print("\nFINAL CHATBOT OUTPUT:")
print(response['response'])

1. Downloading Hugging Face embedding model...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2. Initializing Chroma DB with HF Embeddings...
   Indexing medical research into the database...

--- Patient Question ---
Can you tell me if eating Omega-3 is good for my heart, and why?

--- Retrieved Research (Cardio Review) ---
Cardio Review 2025: Regular consumption of Omega-3 fatty acids reduces the risk of arrhythmias and decreases triglyceride levels in patients with a history of heart disease.

--- Generating Patient Response via Ollama ---

FINAL CHATBOT OUTPUT:
I'm happy to help!

According to the research, eating Omega-3 fatty acids can be beneficial for your heart. Specifically, regular consumption of Omega-3 has been shown to:

1. **Reduce the risk of arrhythmias**: This means that Omega-3 can help prevent irregular heartbeats, which can be a concern for people with a history of heart disease.
2. **Decrease triglyceride levels**: Triglycerides are a type of fat in your blood. High levels can increase the risk of heart disease. Omega-3 has been found to help lower triglyceride levels, which can be beneficial for overall heart health.

So, to answer your question, eating Omega-3 can be good for your heart because it may help reduce the risk of arrhythmias and lower triglyceride levels, which can contribute to a healthier heart.